server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/link_nest_db?useSSL=false&serverTimezone=UTC
    username: root
    password: 156651eqeq
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
